name: com.newrelic.redis
description: Reports status and metrics for redis service
protocol_version: 1
os: linux

commands:
  metrics:
    command:
      - ./nr-redis
      - --metrics
    interval: 15

  inventory:
    command:
      - ./nr-redis
      - --inventory
    prefix: config/redis
    interval: 60
